tap "Seanstoppable/random"
tap "caskroom/cask"
tap "caskroom/versions"
tap "universal-ctags/universal-ctags"

brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]

brew "awscli"
brew "aws-shell"
brew "git"
brew "gnupg"
brew "grip"
brew "hadolint"
brew "htop"
brew "lz4"
brew "peco"
brew "pwgen"
brew "rg"
brew "shellcheck"
brew "the_silver_searcher"
brew "tig"
brew "vim"
brew "watch"
brew "wget"
brew "yank"
brew "zsh"
brew "zsh-completions"

cask "alfred"
#cask "bitbar"
cask "blockblock"
cask "cyberduck"
#cask "dnscrypt"
cask "docker"
cask "flux"
cask "gimp"
cask "hammerspoon"
cask "iterm2"
cask "libreoffice"
cask "keepassxc"
cask "keka"
#cask "oversight"
cask "postman"
#cask "qbittorrent"
#cask "veracrypt"
cask "vlc"
cask "yed"
