#!/bin/sh
#
# Hook that rejects files containing words in blacklist.

echo "TEST"

BLACKLIST="puts\|println"

for FILE in `git diff --cached --name-only` ; do
    if grep -wq $BLACKLIST $FILE; then
      echo "$FILE contains one or more blacklisted words ($BLACKLIST)."
      echo "You can skip this check with --no-verify."
      exit 1
    fi
done
